#filePath=src/test/resources/config.properties

## execution env => local
executionEnv=local
#appUrl=

#execution env => remote (for grid)
#executionEnv=local
#gridUrl=

#browser
browser=chrome
#browser=firefox
#browser=edge
#browser=safari

#os
os=Windows
#os=Mac